name: DevSecOps Azure PoC

on:
  workflow_dispatch:
    inputs:
      target_job:
        description: 'Job to run (security-checks, build-deploy, dast-scan)'
        required: true
        default: 'security-checks'

env:
  AZURE_RG: devsecops-node-rg
  AZURE_WEBAPP_NAME: ntms-secure-nodejs-app
  LOCATION: centralindia

permissions:
  actions: read
  contents: read
  security-events: write  # Required for CodeQL scan results to be uploaded

jobs:
  security-checks:
    name: Code & Infra Security Scanning
    if: ${{ github.event.inputs.target_job == 'security-checks' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: CodeQL Init
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: CodeQL Analyze
        uses: github/codeql-action/analyze@v3

      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          scanArguments: "--regex --entropy=False ."

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov on Bicep Templates
        run: checkov -d ./infra --skip-check CKV_AZURE_213,CKV_AZURE_15,CKV_AZURE_17,CKV_AZURE_67,CKV_AZURE_18,CKV_AZURE_71,3CKV_AZURE_213,CKV_AZURE_225,CKV_AZURE_212,CKV_AZURE_78,CKV_AZURE_222,CKV_AZURE_16

  build-deploy:
    name: Build & Deploy to Azure
    if: ${{ github.event.inputs.target_job == 'build-deploy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: az group create --name $AZURE_RG --location $LOCATION

      - name: Deploy Bicep Template
        run: az deployment group create --resource-group $AZURE_RG --template-file infra/main.bicep

      - name: Deploy App to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./app

  dast-scan:
   
   name: OWASP ZAP DAST Scan
   if: ${{ github.event.inputs.target_job == 'dast-scan' }}
   env:
    AZURE_RG: devsecops-node-rg
    AZURE_WEBAPP_NAME: ntms-secure-nodejs-app
    LOCATION: centralindia
   runs-on: ubuntu-latest
   steps:
    - name: Run ZAP Baseline Scan
      run: |
        docker run --rm -v $(pwd):/zap/wrk/:rw \
          ghcr.io/zaproxy/zap-extensions:stable-baseline \
          -t https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net \
          -r zap_report.html || echo "ZAP scan failed, continuing for report"

    - name: Upload ZAP Report
      if: success() || failure()  # Upload even if ZAP errors
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: zap_report.html
